# Generated by Django 3.0.7 on 2020-06-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_document_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='hash',
        ),
    ]
