# Generated by Django 3.0.7 on 2020-06-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_document_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.ImageField(upload_to='image'),
        ),
    ]
